env:
  browser: true
  es6: true
  commonjs: true
  node: true
  jest: true
settings:
  react:
    version: 'detect'
parser: '@typescript-eslint/parser'
parserOptions:
  project: './configs/tslint.json'
plugins:
  - 'jsx-a11y'
  - 'jest'
  - 'react-hooks'
  - 'react'
  - '@typescript-eslint'
extends:
  - 'plugin:jsx-a11y/recommended'
  - 'plugin:jest/recommended'
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  # Prettier overrides
  - 'prettier'
  - 'prettier/react'
  - 'prettier/@typescript-eslint'
rules:
  prefer-const: error
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: error
overrides:
  - files:
      - '*.ts'
      - '*.tsx'
    rules:
      '@typescript-eslint/no-unused-vars': error

      react/prop-types: off
      react/display-name: off
      '@typescript-eslint/explicit-function-return-type': off
      '@typescript-eslint/no-var-requires': off
      '@typescript-eslint/no-empty-interface': off
      '@typescript-eslint/camelcase': off
      '@typescript-eslint/no-triple-slash-reference': off
      '@typescript-eslint/no-non-null-assertion': off
      '@typescript-eslint/ban-ts-ignore': off
      '@typescript-eslint/no-use-before-define': off
